'use strict';
const $=(id)=>document.getElementById(id);const message=(text,error=false)=>{const box=$('form-message');box.textContent=text;box.classList.toggle('error',error);box.hidden=false};
document.querySelectorAll('.auth-tabs button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.auth-tabs button').forEach(x=>x.classList.toggle('active',x===button));$('login-form').hidden=button.dataset.tab!=='login';$('register-form').hidden=button.dataset.tab!=='register';$('form-message').hidden=true});
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body.detail||'请求失败');return body}
function showUser(user){$('guest-card').hidden=true;$('profile-card').hidden=false;$('profile-name').textContent=user.username;$('profile-email').textContent=user.email;$('profile-role').textContent=user.role==='admin'?'管理员':'玩家';$('profile-created').textContent=new Date(user.createdAt).toLocaleDateString('zh-CN');$('admin-link').hidden=user.role!=='admin'}
$('login-form').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{const data=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});showUser(data.user)}catch(error){message(error.message,true)}};
$('register-form').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{const data=await api('/api/v1/auth/register',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});message(data.message);event.currentTarget.reset()}catch(error){message(error.message,true)}};
$('logout-button').onclick=async()=>{await api('/api/v1/auth/logout',{method:'POST'});location.reload()};
(async()=>{const params=new URLSearchParams(location.search);if(params.get('verified'))message(params.get('verified')==='1'?'邮箱验证成功，现在可以登录了。':'验证链接无效或已经过期。',params.get('verified')!=='1');try{const data=await api('/api/v1/auth/me');showUser(data.user)}catch{}})();
